apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-green-deployment         # EXACT — do NOT change
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-api
      slot: green
  template:
    metadata:
      labels:
        app: sentiment-api
        slot: green                         # EXACT slot label
    spec:
      containers:
        - name: sentiment-api
          image: bilalaskari/sentiment-api:stable   # replace username
          ports:
            - containerPort: 5000
